let colgateData = [
    {
        img: 'image/Col.jpeg',
        colName: 'Colgate charcoal',
        currPrice: '220',
        oldPrice: '250',
        disc: '10',
    },
    {
        img: 'image/Col1.jpeg',
        colName: 'Colgate MaxFresh',
        currPrice: '320',
        oldPrice: '350',
        disc: '18',
    },
    {
        img: 'image/Col2.png',
        colName: 'Colgate Total Active',
        currPrice: '380',
        oldPrice: '400',
        disc: '15',
    },
    {
        img: 'image/Col3.jpeg',
        colName: 'Colgate Sensitive',
        currPrice: '420',
        oldPrice: '450',
        disc: '10',
    },
    {
        img: 'image/col4.jpeg',
        colName: 'Colgate VedShakti',
        currPrice: '300',
        oldPrice: '350',
        disc: '20',
    },
    {
        img: 'image/col5.jpg',
        colName: 'Colgate Amino Shakti',
        currPrice: '132',
        oldPrice: '140',
        disc: '8',
    },
    {
        img: 'image/col6.jpg',
        colName: 'Colgate Strong Teeth',
        currPrice: '319',
        oldPrice: '330',
        disc: '18',
    },
    {
        img: 'image/col7.jpg',
        colName: 'Dabur Red Toothpaste',
        currPrice: '299',
        oldPrice: '430',
        disc: '50',
    },
]

const mobileData = [
    {
        img: 'image/mobiles/mob1.jpg',
        mobName: 'realme NARZO 80x 5G',
        currPrice: '11,498',
        oldPrice: '15,999',
        disc: '28',
    },
    {
        img: 'image/mobiles/mob2.jpg',
        mobName: 'Redmi A4 5G (Sparkle Purple, 4GB RAM, 64GB Storage)',
        currPrice: '7,499',
        oldPrice: '10,999',
        disc: '32',
    },
    {
        img: 'image/mobiles/mob3.webp',
        mobName: 'Samsung Galaxy M06 5G (Sage Green, 4GB RAM, 64GB Storage)',
        currPrice: '7,499',
        oldPrice: '12,499',
        disc: '40',
    },
    {
        img: 'image/mobiles/mob4.webp',
        mobName: 'iQOO Z10 Lite 5G (Titanium Blue, 4GB RAM, 128GB Storage)',
        currPrice: '9,989',
        oldPrice: '13,999',
        disc: '29',
    },
    {
        img: 'image/mobiles/mob5.webp',
        mobName: 'OnePlus Nord CE4 Lite 5G (Super Silver, 8GB RAM, 128GB',
        currPrice: '15,999',
        oldPrice: '20,999',
        disc: '24',
    },
    {
        img: 'image/mobiles/mob6.webp',
        mobName: 'Redmi 13 5G Prime Edition, Black Diamond, 8GB+128GB',
        currPrice: '10,999',
        oldPrice: '19,999',
        disc: '45',
    },
    {
        img: 'image/mobiles/mob7.webp',
        mobName: 'OnePlus Nord 5 | Snapdragon 8s Gen 3 | Stable 144FPS',
        currPrice: '31,998',
        oldPrice: '34,999',
        disc: '9',
    },
    {
        img: 'image/mobiles/mob8.webp',
        mobName: 'Lava Bold N1 Pro (Titanium Gold, 4 GB RAM, 128 GB Storage)',
        currPrice: '6,599',
        oldPrice: '8,339',
        disc: '21',
    },
    {
        img: 'image/mobiles/mob9.webp',
        mobName: 'POCO C71, Desert Gold (6GB, 128GB)',
        currPrice: '6,799',
        oldPrice: '9,999',
        disc: '32',
    },
    {
        img: 'image/mobiles/mob10.jpg',
        mobName: 'POCO M7 5G, Ocean Blue (6GB, 128GB)',
        currPrice: '8,489',
        oldPrice: '12,999',
        disc: '35',
    },
]

const footwearData = [
    {
        img: 'image/others/shoe1.webp',
        brand: 'BRUTON ',
        mobName: 'FITMAN Loafers For Men  (Blue , 7)',
        currPrice: '238',
        oldPrice: '1,323',
        disc: '82',
    },
    {
        img: 'image/others/shoe2.webp',
        brand: 'BRUTON',
        mobName: 'Fit-Man Slip On S',
        currPrice: '195',
        oldPrice: '1323',
        disc: '85',
    },
    {
        img: 'image/others/shoe3.webp',
        brand: 'BOTOWI',
        mobName: 'Clogs For Men',
        currPrice: '199',
        oldPrice: '599',
        disc: '66',
    },
    {
        img: 'image/others/shoe4.webp',
        brand: 'BSSHOSE',
        mobName: 'Casuals For Men',
        currPrice: '175',
        oldPrice: '499',
        disc: '64',
    },
    {
        img: 'image/others/shoe5.webp',
        brand: 'KANEGGYE',
        mobName: 'For Men',
        currPrice: '196',
        oldPrice: '699',
        disc: '72',
    },
    {
        img: 'image/others/shoe6.webp',
        brand: 'AJANTA',
        mobName: 'Casual PVC Water.',
        currPrice: '269',
        oldPrice: '699',
        disc: '61',
    },
    {
        img: 'image/others/shoe7.webp',
        brand: 'BRUTON',
        mobName: 'Loafers For Men',
        currPrice: '218',
        oldPrice: '609',
        disc: '83',
    },
    {
        img: 'image/others/shoe8.webp',
        brand: ' Koburg',
        mobName: 'Strap Sports Sanda',
        currPrice: '499',
        oldPrice: '2,444',
        disc: '79',
    },
    {
        img: 'image/others/shoe9.webp',
        brand: 'Trendmode',
        mobName: 'Velcro Strappy San',
        currPrice: '398',
        oldPrice: '599',
        disc: '43',
    },
    {
        img: 'image/others/shoe10.webp',
        brand: 'BOOMER CUBS',
        mobName: 'Velcro Peep Toes Fo',
        currPrice: '475',
        oldPrice: '1,544',
        disc: '53',
    },
]